### ISSUE TITLE
Can you help me to get source code of book?

### ISSUE THREAD

**Issue by y00rb** [lorenzo-stoakes/linux-gorman-book-notes#1]
Hi Lorenzo Stoakes
I'm a programmer from China, recently, I reading the book <<understanding the linux virtual memory manager>> but I don't found out the source code. You made created notes for the books, Can you tell me where can get the source code?

**Comment by ljskernel** [comment]
Hello from the UK! I don't think there is particular source code as he's discussing the linux kernel, which of course is available everywhere, https://www.kernel.org/ or https://github.com/torvalds/linux

If you want to look at more up to date analyses of the mm code you can have a look at my (incomplete but still some decent coverage) notes at https://github.com/lorenzo-stoakes/linux-vm-notes and https://github.com/lorenzo-stoakes/linux-mm-notes

**Comment by y00rb** [comment]
Sorry for late reply, firstly, I would like Thank you for help, maybe I need follow your articles that is good choice!
